import Head from 'next/head'

import Header from '../components/Header'


export default function Home() {
  return (
    
    <div className='flex flex-col items-center'>
        <Head>
        <title>Sidebar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
    
  




    
    </div>
  )
}
