import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Example from './components/Combobox'
import Header from './components/Header'
import Navbar from './components/Navbar'

export default function Home() {
  return (
    
    <div className='flex flex-col items-center'>
        <Head>
        <title>Sidebar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
    
  




    
    </div>
  )
}
